<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace Tls;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Log</code>
 */
class Log extends \Google\Protobuf\Internal\Message
{
    /**
     * UNIX Time Format
     *
     * Generated from protobuf field <code>int64 Time = 1;</code>
     */
    protected $Time = 0;
    /**
     * Generated from protobuf field <code>repeated .pb.LogContent Contents = 2;</code>
     */
    private $Contents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $Time
     *           UNIX Time Format
     *     @type array<\Tls\LogContent>|\Google\Protobuf\Internal\RepeatedField $Contents
     * }
     */
    public function __construct($data = NULL) {
        \Tls\Metadata\Log::initOnce();
        parent::__construct($data);
    }

    /**
     * UNIX Time Format
     *
     * Generated from protobuf field <code>int64 Time = 1;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->Time;
    }

    /**
     * UNIX Time Format
     *
     * Generated from protobuf field <code>int64 Time = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->Time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.LogContent Contents = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContents()
    {
        return $this->Contents;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.LogContent Contents = 2;</code>
     * @param array<\Tls\LogContent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tls\LogContent::class);
        $this->Contents = $arr;

        return $this;
    }

}

