<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

namespace Tls;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.LogGroupList</code>
 */
class LogGroupList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pb.LogGroup LogGroups = 1;</code>
     */
    private $LogGroups;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Tls\LogGroup>|\Google\Protobuf\Internal\RepeatedField $LogGroups
     * }
     */
    public function __construct($data = NULL) {
        \Tls\Metadata\Log::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pb.LogGroup LogGroups = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogGroups()
    {
        return $this->LogGroups;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.LogGroup LogGroups = 1;</code>
     * @param array<\Tls\LogGroup>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Tls\LogGroup::class);
        $this->LogGroups = $arr;

        return $this;
    }

}

