<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log.proto

namespace Tls;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Tls\Metadata\Log;

/**
 * Generated from protobuf message <code>pb.LogGroupList</code>
 */
class LogGroupList extends Message
{
    /**
     * Generated from protobuf field <code>repeated .pb.LogGroup LogGroups = 1;</code>
     */
    private $LogGroups;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type array<\Tls\LogGroup>|\Google\Protobuf\Internal\RepeatedField $LogGroups
     *                                                                    }
     */
    public function __construct($data = null)
    {
        Log::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pb.LogGroup LogGroups = 1;</code>
     *
     * @return RepeatedField
     */
    public function getLogGroups()
    {
        return $this->LogGroups;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.LogGroup LogGroups = 1;</code>
     *
     * @param  array<LogGroup>|RepeatedField  $var
     * @return $this
     */
    public function setLogGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, LogGroup::class);
        $this->LogGroups = $arr;

        return $this;
    }
}
