<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log.proto

namespace Tls;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Generated from protobuf message <code>pb.LogGroup</code>
 */
class LogGroup extends Message
{
    /**
     * Generated from protobuf field <code>repeated .pb.Log Logs = 1;</code>
     */
    private $Logs;

    /**
     * Generated from protobuf field <code>string Source = 2;</code>
     */
    protected $Source = '';

    /**
     * Generated from protobuf field <code>repeated .pb.LogTag LogTags = 3;</code>
     */
    private $LogTags;

    /**
     * Generated from protobuf field <code>string FileName = 4;</code>
     */
    protected $FileName = '';

    /**
     *该字段暂无效用
     *
     * Generated from protobuf field <code>string ContextFlow = 5;</code>
     */
    protected $ContextFlow = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type array<\Tls\Log>|\Google\Protobuf\Internal\RepeatedField $Logs
     * @type string $Source
     * @type array<\Tls\LogTag>|\Google\Protobuf\Internal\RepeatedField $LogTags
     * @type string $FileName
     * @type string $ContextFlow
     *              该字段暂无效用
     *              }
     */
    public function __construct($data = null)
    {
        Metadata\Log::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Log Logs = 1;</code>
     *
     * @return RepeatedField
     */
    public function getLogs()
    {
        return $this->Logs;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Log Logs = 1;</code>
     *
     * @param  array<Log>|RepeatedField  $var
     * @return $this
     */
    public function setLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Log::class);
        $this->Logs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Source = 2;</code>
     *
     * @return string
     */
    public function getSource()
    {
        return $this->Source;
    }

    /**
     * Generated from protobuf field <code>string Source = 2;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, true);
        $this->Source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.LogTag LogTags = 3;</code>
     *
     * @return RepeatedField
     */
    public function getLogTags()
    {
        return $this->LogTags;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.LogTag LogTags = 3;</code>
     *
     * @param  array<LogTag>|RepeatedField  $var
     * @return $this
     */
    public function setLogTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, LogTag::class);
        $this->LogTags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FileName = 4;</code>
     *
     * @return string
     */
    public function getFileName()
    {
        return $this->FileName;
    }

    /**
     * Generated from protobuf field <code>string FileName = 4;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkString($var, true);
        $this->FileName = $var;

        return $this;
    }

    /**
     *该字段暂无效用
     *
     * Generated from protobuf field <code>string ContextFlow = 5;</code>
     *
     * @return string
     */
    public function getContextFlow()
    {
        return $this->ContextFlow;
    }

    /**
     *该字段暂无效用
     *
     * Generated from protobuf field <code>string ContextFlow = 5;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setContextFlow($var)
    {
        GPBUtil::checkString($var, true);
        $this->ContextFlow = $var;

        return $this;
    }
}
